import { Site } from '../sites/site';
import { State } from '../lookup/state';
import { FogInspectionResult, FogReasonForInspection } from './fog-inspection-enums';
import { PropertyType } from '../../enums/property-type.enum';
import { FacilityType } from '../../enums/facility-type.enum';

export interface FogInspection {
    id: number;
    site?: Site | null;
    inspectionDate?: string;
    submissionId?: string;
    propertyBusinessName?: string;
    propertyType?: PropertyType;
    propertyStreetNumber?: string;
    propertyStreetName?: string;
    propertyNumber?: string;
    propertyCity?: string;
    propertyState?: State | null;
    propertyZip?: string;
    mailingCompanyName?: string;
    mailingContactName?: string;
    mailingStreetNumber?: string;
    mailingStreetName?: string;
    mailingNumber?: string;
    mailingCity?: string;
    mailingState?: State | null;
    mailingZip?: string;
    mailingPhoneNumber?: string;
    mailingEmailAddress?: string;
    inspectorUser?: { id?: number } | null;
    inspectorCompanyName?: string;
    inspectorJobTitle?: string;
    inspectorContactName?: string;
    inspectorAddress?: string;
    inspectorCity?: string;
    inspectorState?: string;
    inspectorZip?: string;
    inspectorWorkNumber?: string;
    inspectorCellNumber?: string;
    inspectorFaxNumber?: string;
    fogGeneratorPhoneNumber?: string;
    fogGeneratorEmailAddress?: string;
    facilityType?: FacilityType;
    reasonForInspection?: FogReasonForInspection;
    interceptorType?: string;
    interceptorOtherDescription?: string;
    interceptorCapacity?: number;
    interceptorCapacityType?: number;
    interceptorLocationDescription?: string;
    interceptorLatitude?: number | null;
    interceptorLongitude?: number | null;
    interceptorComments?: string;
    maintained?: boolean;
    accessible?: boolean;
    pastOverflow?: boolean;
    inletChamberWettingHeight?: string;
    inletChamberGreaseBlanket?: string;
    inletChamberSediments?: string;
    outletChamberWettingHeight?: string;
    outletChamberGreaseBlanket?: string;
    outletChamberSediments?: string;
    inletTeeIntact?: boolean;
    outletTeeIntact?: boolean;
    inletTeeVisible?: boolean | null;
    outletTeeVisible?: boolean | null;
    sampledFrom?: string;
    samplingPointAccessible?: boolean;
    samplingPointClean?: boolean;
    inletTotalCapacityPercent?: number;
    outletTotalCapacityPercent?: number;
    totalCapacityPercent?: number;
    inspectionResult?: FogInspectionResult;
    signatureContactName?: string;
    signatureDate?: string;
    comments?: string;
    lastTripTicketDate?: string;
    tripTicketInterval?: number;
    needsValidation?: boolean;
    validationNewSite?: boolean;
    validationSiteInformationChanged?: boolean;
    transactionId?: string;
    transactionDate?: string;
    amount?: number;
    amountShare?: number;
    emailPdf?: boolean;
    createdTime?: string;
    updatedTime?: string;
}
