export interface BackflowTest {
    id: number;
    site?: { id: number; accountNumber?: string } | null;
    createdTime?: string;
    updatedTime?: string;
    submissionId?: string;
    jobNumber?: string;
    professionalId?: number;
    bpatId?: number;
    bpatLicenseNumber?: string;
    bpatLicenseExpiration?: string;
    bpatCompanyName?: string;
    bpatContactName?: string;
    bpatState?: { id?: number; name?: string; code?: string } | null;
    accountNumber?: string;
    propertyBusinessName?: string;
    propertyType?: number;
    propertyStreetNumber?: string;
    propertyStreetName?: string;
    propertyNumber?: string;
    propertyCity?: string;
    propertyState?: { id?: number; name?: string; code?: string } | null;
    propertyZip?: string;
    mailingCompanyName?: string;
    mailingContactName?: string;
    mailingState?: { id?: number; name?: string; code?: string } | null;
    deviceType?: string;
    manufacturer?: string;
    model?: string;
    size?: string;
    serialNumber?: string;
    unknownSerialNumber?: boolean;
    locationDescription?: string;
    hazardType?: string;
    reasonForTest?: number;
    testDate?: string;
    initialTestDate?: string;
    finalTestDate?: string;
    expirationDate?: string;
    testResult?: number;
    properlyInstalled?: boolean;
    nonPotable?: boolean;
    gaugeNonPotable?: boolean;
    meterNumber?: string;
    permitNumber?: string;
    ossf?: boolean;
    comments?: string;
    isCurrent?: boolean;
    disapproved?: boolean;
    outOfService?: boolean;
    outOfServiceDate?: string;
    approvalDate?: string;
    approvedById?: number;
    transactionId?: string;
    amount?: number;
    rejected?: boolean;
    rejectedById?: number;
    rejectedDate?: string;
    rejectedReason?: string;
    needsValidation?: boolean;
}
