import { Professional } from '../professionals/professional';
import { ProfessionalUser } from '../professionals/professional-user';
import { Site } from '../sites/site';
import { State } from '../lookup/state';
import { WaterSupplierUser } from '../users/water-supplier-user';

export interface BackflowTest {
    id: number;
    site?: Site | null;
    createdTime?: string;
    updatedTime?: string;
    submissionId?: string;
    jobNumber?: string;
    professional?: Professional | null;
    bpat?: ProfessionalUser | null;
    bpatLicenseNumber?: string;
    bpatLicenseExpiration?: string;
    bpatCompanyName?: string;
    bpatContactName?: string;
    bpatState?: State | null;
    accountNumber?: string;
    propertyBusinessName?: string;
    propertyType?: number;
    propertyStreetNumber?: string;
    propertyStreetName?: string;
    propertyNumber?: string;
    propertyCity?: string;
    propertyState?: State | null;
    propertyZip?: string;
    mailingCompanyName?: string;
    mailingContactName?: string;
    mailingState?: State | null;
    deviceType?: string;
    manufacturer?: string;
    model?: string;
    size?: string;
    serialNumber?: string;
    unknownSerialNumber?: boolean;
    locationDescription?: string;
    hazardType?: string;
    reasonForTest?: number;
    testDate?: string;
    initialTestDate?: string;
    finalTestDate?: string;
    expirationDate?: string;
    testResult?: number;
    properlyInstalled?: boolean;
    nonPotable?: boolean;
    gaugeNonPotable?: boolean;
    meterNumber?: string;
    permitNumber?: string;
    ossf?: boolean;
    comments?: string;
    isCurrent?: boolean;
    disapproved?: boolean;
    outOfService?: boolean;
    outOfServiceDate?: string;
    approvalDate?: string;
    approvedBy?: WaterSupplierUser | null;
    transactionId?: string;
    amount?: number;
    rejected?: boolean;
    rejectedBy?: WaterSupplierUser | null;
    rejectedDate?: string;
    rejectedReason?: string;
    needsValidation?: boolean;
}
