// <auto-generated />
using System;
using Envirotrax.App.Server.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Envirotrax.App.Server.Data.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260203022659_ProfessionalServices")]
    partial class ProfessionalServices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Envirotrax.App.Server.Data.Models.Professionals.Professional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("HasBackflowTesting")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCsiInspection")
                        .HasColumnType("bit");

                    b.Property<bool>("HasFogInspection")
                        .HasColumnType("bit");

                    b.Property<bool>("HasFogTransportation")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWiseGuys")
                        .HasColumnType("bit");

                    b.Property<bool>("HidePublicListing")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("WebSiteUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ParentId");

                    b.HasIndex("StateId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Professionals");
                });

            modelBuilder.Entity("Envirotrax.App.Server.Data.Models.Professionals.ProfessionalUser", b =>
                {
                    b.Property<int>("ProfessionalId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ContactName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ProfessionalId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProfessionalUsers");
                });

            modelBuilder.Entity("Envirotrax.App.Server.Data.Models.States.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("Envirotrax.App.Server.Data.Models.Users.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Envirotrax.App.Server.Data.Models.Users.WaterSupplierUser", b =>
                {
                    b.Property<int>("WaterSupplierId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WaterSupplierId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("WaterSupplierUsers");
                });

            modelBuilder.Entity("Envirotrax.App.Server.Data.Models.WaterSuppliers.GeneralSettings", b =>
                {
                    b.Property<int>("WaterSupplierId")
                        .HasColumnType("int");

                    b.Property<bool>("AdministrativeOnly")
                        .HasColumnType("bit");

                    b.Property<decimal>("BackflowCommercialTestFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BackflowCommercialTestFeeWsShare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BackflowResidentialTestFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BackflowResidentialTestFeeWsShare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("BackflowTesting")
                        .HasColumnType("bit");

                    b.Property<bool>("BpatsRequireInsurance")
                        .HasColumnType("bit");

                    b.Property<decimal>("BpatsRequireInsuranceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("BpatsRequireIrrigationLicense")
                        .HasColumnType("bit");

                    b.Property<decimal>("CsiCommercialInspectionFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CsiCommercialInspectionFeeWsShare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("CsiInspections")
                        .HasColumnType("bit");

                    b.Property<bool>("CsiInspectorsRequireInsurance")
                        .HasColumnType("bit");

                    b.Property<decimal>("CsiInspectorsRequireInsuranceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CsiResidentialInspectionFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CsiResidentialInspectionFeeWsShare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("FogProgram")
                        .HasColumnType("bit");

                    b.Property<decimal>("FogTransportFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FogTransportFeeWsShare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("FogTransportersRequireInsurance")
                        .HasColumnType("bit");

                    b.Property<decimal>("FogTransportersRequireInsuranceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("FogVehiclesRequireInspection")
                        .HasColumnType("bit");

                    b.Property<bool>("FogVehiclesRequirePermit")
                        .HasColumnType("bit");

                    b.Property<bool>("LockBpatRegistrations")
                        .HasColumnType("bit");

                    b.Property<bool>("LockCsiRegistrations")
                        .HasColumnType("bit");

                    b.Property<bool>("LockFogInspectorRegistrations")
                        .HasColumnType("bit");

                    b.Property<bool>("LockFogTransporterRegistrations")
                        .HasColumnType("bit");

                    b.Property<bool>("NewSitesLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("PrivacyRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("WiseGuys")
                        .HasColumnType("bit");

                    b.HasKey("WaterSupplierId");

                    b.ToTable("GeneralSettings");
                });

            modelBuilder.Entity("Envirotrax.App.Server.Data.Models.WaterSuppliers.WaterSupplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LetterAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LetterCity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LetterCompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LetterContactAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LetterContactCity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LetterContactCompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LetterContactContactName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LetterContactEmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LetterContactFaxNumber")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LetterContactName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LetterContactPhoneNumber")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("LetterContactStateId")
                        .HasColumnType("int");

                    b.Property<string>("LetterContactZipCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("LetterStateId")
                        .HasColumnType("int");

                    b.Property<string>("LetterZipCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PwsId")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("LetterContactStateId");

                    b.HasIndex("LetterStateId");

                    b.HasIndex("ParentId");

                    b.HasIndex("StateId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("WaterSuppliers");
                });

            modelBuilder.Entity("Envirotrax.App.Server.Data.Models.WaterSuppliers.WaterSupplierProfessional", b =>
                {
                    b.Property<int>("WaterSupplierId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessionalId")
                        .HasColumnType("int");

                    b.HasKey("WaterSupplierId", "ProfessionalId");

                    b.HasIndex("ProfessionalId");

                    b.ToTable("WaterSupplierProfessionals");
                });

            modelBuilder.Entity("Envirotrax.App.Server.Data.Models.Professionals.Professional", b =>
                {
                    b.HasOne("Envirotrax.App.Server.Data.Models.Users.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Envirotrax.App.Server.Data.Models.Users.AppUser", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Envirotrax.App.Server.Data.Models.Professionals.Professional", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Envirotrax.App.Server.Data.Models.States.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Envirotrax.App.Server.Data.Models.Users.AppUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Parent");

                    b.Navigation("State");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Envirotrax.App.Server.Data.Models.Professionals.ProfessionalUser", b =>
                {
                    b.HasOne("Envirotrax.App.Server.Data.Models.Professionals.Professional", "Professional")
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Envirotrax.App.Server.Data.Models.Users.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professional");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Envirotrax.App.Server.Data.Models.Users.WaterSupplierUser", b =>
                {
                    b.HasOne("Envirotrax.App.Server.Data.Models.Users.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Envirotrax.App.Server.Data.Models.WaterSuppliers.WaterSupplier", "WaterSupplier")
                        .WithMany()
                        .HasForeignKey("WaterSupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WaterSupplier");
                });

            modelBuilder.Entity("Envirotrax.App.Server.Data.Models.WaterSuppliers.GeneralSettings", b =>
                {
                    b.HasOne("Envirotrax.App.Server.Data.Models.WaterSuppliers.WaterSupplier", "WaterSupplier")
                        .WithMany()
                        .HasForeignKey("WaterSupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WaterSupplier");
                });

            modelBuilder.Entity("Envirotrax.App.Server.Data.Models.WaterSuppliers.WaterSupplier", b =>
                {
                    b.HasOne("Envirotrax.App.Server.Data.Models.Users.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Envirotrax.App.Server.Data.Models.Users.AppUser", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Envirotrax.App.Server.Data.Models.States.State", "LetterContactState")
                        .WithMany()
                        .HasForeignKey("LetterContactStateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Envirotrax.App.Server.Data.Models.States.State", "LetterState")
                        .WithMany()
                        .HasForeignKey("LetterStateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Envirotrax.App.Server.Data.Models.WaterSuppliers.WaterSupplier", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Envirotrax.App.Server.Data.Models.States.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Envirotrax.App.Server.Data.Models.Users.AppUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("LetterContactState");

                    b.Navigation("LetterState");

                    b.Navigation("Parent");

                    b.Navigation("State");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Envirotrax.App.Server.Data.Models.WaterSuppliers.WaterSupplierProfessional", b =>
                {
                    b.HasOne("Envirotrax.App.Server.Data.Models.Professionals.Professional", "Professional")
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Envirotrax.App.Server.Data.Models.WaterSuppliers.WaterSupplier", "WaterSupplier")
                        .WithMany()
                        .HasForeignKey("WaterSupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professional");

                    b.Navigation("WaterSupplier");
                });
#pragma warning restore 612, 618
        }
    }
}
